apiVersion: apps/v1
kind: Deployment
metadata:
  name: notf-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notf-service
  template:
    metadata:
      labels:
        app: notf-service
    spec:
      containers:
      - name: notf-container
        image: 9874694577/notf-service:${{ github.sha }}
        imagePullPolicy: Always
        ports:
        - containerPort: 7070  # gRPC
        - containerPort: 8082  # HTTP
        envFrom:
        - configMapRef:
            name: notf-config
        - secretRef:
            name: notf-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"

